// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04BxiissKbzITHk2TPvY8wPRWNabOlQA',
    appId: '1:633775424665:web:8528efff44febee2842408',
    messagingSenderId: '633775424665',
    projectId: 'financialtrac',
    authDomain: 'financialtrac.firebaseapp.com',
    storageBucket: 'financialtrac.appspot.com',
    measurementId: 'G-53F0VEGCB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuA4Znmap6wBlD9CwmCPiQuN5eotquqk',
    appId: '1:633775424665:android:65a96b86a61fa101842408',
    messagingSenderId: '633775424665',
    projectId: 'financialtrac',
    storageBucket: 'financialtrac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgO0dGiw1s8HNnsJaBHaUwJdxJPIG_1yY',
    appId: '1:633775424665:ios:3a48fd7492e4c649842408',
    messagingSenderId: '633775424665',
    projectId: 'financialtrac',
    storageBucket: 'financialtrac.appspot.com',
    iosBundleId: 'com.example.financialTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgO0dGiw1s8HNnsJaBHaUwJdxJPIG_1yY',
    appId: '1:633775424665:ios:3260f501aa735b8c842408',
    messagingSenderId: '633775424665',
    projectId: 'financialtrac',
    storageBucket: 'financialtrac.appspot.com',
    iosBundleId: 'com.example.financialTracker.RunnerTests',
  );
}
